# Generated by Django 3.2.3 on 2021-05-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conseil',
            options={'verbose_name': 'conseil', 'verbose_name_plural': 'conseils'},
        ),
    ]
