# Generated by Django 3.2.3 on 2021-05-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='images',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default=1, upload_to='images_banner'),
            preserve_default=False,
        ),
    ]
