# Generated by Django 3.2.3 on 2021-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_auto_20210520_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
