# Generated by Django 3.2.3 on 2021-05-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_auto_20210520_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
    ]
