# Generated by Django 3.2.3 on 2021-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_alter_newsletter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('images', models.ImageField(upload_to='imagebanner')),
                ('titre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'ImageBanner',
                'verbose_name_plural': 'ImagesBanners',
            },
        ),
    ]
