# Generated by Django 3.2.3 on 2021-05-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0006_imagebanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageBanner',
        ),
    ]
